### ISSUE TITLE
Ability for batch download

### ISSUE THREAD

**Issue by vmdude** [manga-py/manga-py#361]
# Feature request

**Is your feature request related to a problem? Please describe.**
As of today, I'm using `manga-py` through a custom python app to be able to bulk download a list of manga based on an yaml file input, which is handy to keep followed manga up to date.

**Describe the solution you'd like**
Having a batch download option in `manga-py` could be useful (from yaml/json input for instance)

**Describe alternatives you've considered**
I've made a script that loop on a yaml file and trigger `manga-py` for each manga in it, which isn't ideal.

**Additional context**
Input file sample:
```yaml
---
config:
  default_lang: gb
  output_dir: '/Volumes/share/eBook/Manga/'
mangas:
  ### SAMPLE
  # - id: toriko
  #   url: https://mangadex.org/title/28004/jujutsu-kaisen
  #   name: TorikoCustom
  #   lang: fr
  ### END SAMPLE
  - url: https://mangadex.org/title/9570/ajin
  - url: https://manga4life.com/manga/Ao-No-Exorcist
    name: Ao No Exorcist
  ...
  - url: https://manga4life.com/manga/Asadora
```

![image](https://user-images.githubusercontent.com/1384259/103481694-f6947380-4ddc-11eb-9354-4faee74054d8.png)
